spring:
  data:
    redis:
      host: switchback.proxy.rlwy.net
      port: 36268
      password: OLfjCMzleOarhMBaZWYfORVMRQHrZRVm
      ssl:
        enabled: true
logging:
  level:
    org.springframework.data.redis: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Auth-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: Auth Service API
    version: 1.0.0
    description: API document

jwt:
  expiration-access-token: 172800000 # 2 days = 1000 * 60 * 60 * 24 * 2
  expiration-refresh-token: 172800000 # 2 days = 1000 * 60 * 60 * 24 * 2
  secret-key-access-token: 88aca258cbdefc094bc97298383e7fbd3527d3db3e308075598b5578f430bed7 # access-token
  secret-key-refresh-token: e9f8512d47a05a84071745f29cdc6d7bdd9a1e554e6ed56f2547960c5fc7dea9 # refresh-token
