spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/edu-school
#       opaquetoken:
#          client-id:
#          client-secret:
#          introspection-uri:
#  jwt or opquetoken

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: edu-school
  client-id-register: admin-cli
  client-id-login: auth-service
  client-secret: YyupQFGJp4OPF99XZDKjq9rgpfL4aD5B
  username: admin@example.com
  password: 123456

server:
  port: 8080

openapi:
  service:
    server: http://localhost:${server.port}
    title: Keycloak Admin API
    version: 1.0.0
    description: API Documentation for Keycloak Admin Service
springdoc:
  swagger-ui:
    query-config-enabled: false
  api-docs:
    path: /api-docs-json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/