spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth/realms/${KEYCLOAK_REALM}
server:
  port: ${SERVER_PORT}


keycloak:
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
