spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${KEYCLOAK_HOST}:${KEYCLOAK_PORT}/auth/realms/${KEYCLOAK_REALM}
server:
  port: ${SERVER_PORT}

openapi:
  service:
    server: https://${SERVER_HOST}:${SERVER_PORT}
    title: Keycloak Admin API
    version: 1.0.0
    description: API Documentation for Keycloak Admin Service
springdoc:
  swagger-ui:
    query-config-enabled: false
  api-docs:
    path: /api-docs-json

keycloak:
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
