version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: temporal
      MYSQL_DATABASE: temporal
      MYSQL_USER: temporal
      MYSQL_PASSWORD: temporal
    volumes:
      - mysql-data:/var/lib/mysql

  temporal:
    image: temporalio/auto-setup
    ports:
      - "7233:7233"

    environment:
      DB: mysql8
      MYSQL_USER: root
      MYSQL_PWD: temporal
      MYSQL_SEEDS: mysql
      MYSQL_DB: temporal
      TEMPORAL_WEB_ENABLED: true
    depends_on:
      - mysql
  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    ports:
      - "8233:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

volumes:
  mysql-data:
