spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: School-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: School Service API
    version: 1.0.0
    description: API document
