spring:
  gprc:
    client:
      channels:
        user-service:
          address: localhost:9093
  data:
    mongodb:
        uri: mongodb://root:rootpassword@localhost:27017/chatdb

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Chat-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: Chat Service API
    version: 1.0.0
    description: API document